export const RESET_STATE = "RESET_STATE";
export const SET_CURRENT_DOUGH = "SET_CURRENT_DOUGH";
export const SET_CURRENT_SIZE = "SET_CURRENT_SIZE";
export const SET_CURRENT_SAUCE = "SET_CURRENT_SAUCE";
export const EDIT = "EDIT";
export const SET_PIZZA_NAME = "SET_PIZZA_NAME";
export const EDIT_INGREDIENTS = "EDIT_INGREDIENTS";
