export const RESET_STATE = "RESET_STATE";
export const SET_SAUCES = "SET_SAUCES";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SAUCE_CHANGE = "SAUCE_CHANGE";
export const INGREDIENT_INC = "INGREDIENT_INC";
export const INGREDIENT_DEC = "INGREDIENT_DEC";
export const INGREDIENT_CHANGE = "INGREDIENT_CHANGE";
export const INGREDIENT_DROP = "INGREDIENT_DROP";
